#
# BTstack example 'spp_streamer' for ESP32 port
#
# Generated by /home/aehparta/code/tmp/btstack/port/esp32
# On Tue Aug 21 17:38:41 2018

PROJECT_NAME := remote_pwm_ctrl
EXTRA_COMPONENT_DIRS = src

include $(IDF_PATH)/make/project.mk
